"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Actions;
(function (Actions) {
    Actions["blackjack"] = "blackjack";
    Actions["burnCardDown"] = "burnCardDown";
    Actions["burnCardUp"] = "burnCardUp";
    Actions["bust"] = "bust";
    Actions["collectBet"] = "collectBet";
    Actions["collectInsuranceBet"] = "collectInsuranceBet";
    Actions["dealerCardDown"] = "dealerCardDown";
    Actions["dealerCardUp"] = "dealerCardUp";
    Actions["doubleDown"] = "doubleDown";
    Actions["endGame"] = "endGame";
    Actions["endHand"] = "endHand";
    Actions["exposeDealerCard"] = "exposeDealerCard";
    Actions["hit"] = "hit";
    Actions["insurancePayout"] = "insurancePayout";
    Actions["insurance"] = "insurance";
    Actions["lastHand"] = "lastHand";
    Actions["payOut"] = "payOut";
    Actions["placeBet"] = "placeBet";
    Actions["playHand"] = "playHand";
    Actions["playerBetAmount"] = "playerBetAmount";
    Actions["playerCardDown"] = "playerCardDown";
    Actions["playerCardUp"] = "playerCardUp";
    Actions["push"] = "push";
    Actions["setEndCard"] = "setEndCard";
    Actions["shuffle"] = "shuffle";
    Actions["split"] = "split";
    Actions["stand"] = "stand";
    Actions["startGame"] = "startGame";
    Actions["startHand"] = "startHand";
    Actions["surrender"] = "surrender";
})(Actions || (Actions = {}));
exports.default = Actions;
//# sourceMappingURL=actions.js.map