"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Actions;
(function (Actions) {
    Actions[Actions["burnCardDown"] = 0] = "burnCardDown";
    Actions[Actions["burnCardup"] = 1] = "burnCardup";
    Actions[Actions["bust"] = 2] = "bust";
    Actions[Actions["collectBet"] = 3] = "collectBet";
    Actions[Actions["collectInsuranceBet"] = 4] = "collectInsuranceBet";
    Actions[Actions["dealerCardDown"] = 5] = "dealerCardDown";
    Actions[Actions["dealerCardUp"] = 6] = "dealerCardUp";
    Actions[Actions["doubleDown"] = 7] = "doubleDown";
    Actions[Actions["endGame"] = 8] = "endGame";
    Actions[Actions["endHand"] = 9] = "endHand";
    Actions[Actions["exposeDealerCard"] = 10] = "exposeDealerCard";
    Actions[Actions["hit"] = 11] = "hit";
    Actions[Actions["insurancePayout"] = 12] = "insurancePayout";
    Actions[Actions["insurance"] = 13] = "insurance";
    Actions[Actions["lastHand"] = 14] = "lastHand";
    Actions[Actions["payOut"] = 15] = "payOut";
    Actions[Actions["placeBet"] = 16] = "placeBet";
    Actions[Actions["playHand"] = 17] = "playHand";
    Actions[Actions["playerBetAmount"] = 18] = "playerBetAmount";
    Actions[Actions["playerCardDown"] = 19] = "playerCardDown";
    Actions[Actions["playerCardUp"] = 20] = "playerCardUp";
    Actions[Actions["push"] = 21] = "push";
    Actions[Actions["setEndCard"] = 22] = "setEndCard";
    Actions[Actions["shuffle"] = 23] = "shuffle";
    Actions[Actions["split"] = 24] = "split";
    Actions[Actions["stand"] = 25] = "stand";
    Actions[Actions["startGame"] = 26] = "startGame";
    Actions[Actions["startHand"] = 27] = "startHand";
    Actions[Actions["surrender"] = 28] = "surrender";
})(Actions || (Actions = {}));
exports.default = Actions;
//# sourceMappingURL=actions.js.map