module.exports = {
  PLAYER_CARD_DOWN: Symbol(0),
  PLAYER_CARD_UP: Symbol(14),
  DOUBLE_DOWN: Symbol(1),
  BURN_CARD_UP: Symbol(20),
  BURN_CARD_DOWN: Symbol(21),
  SPLIT: Symbol(2),
  HIT: Symbol(3),
  STAND: Symbol(4),
  PUSH: Symbol('push'),
  PLACE_BET: Symbol(19),
  PAY_OUT: Symbol(13),
  COLLECT_BET: Symbol('collect_bet'),
  COLLECT_INSURANCE_BET: Symbol('collect_insurance_bet'),
  INSURANCE: Symbol(5),
  INSURANCE_PAYOUT: Symbol('insurance_payout'),
  SURRENDER: Symbol(6),
  START_HAND: Symbol(7),
  PLAYER_BET_AMOUNT: Symbol(22),
  END_HAND: Symbol(15),
  START_GAME: Symbol(8),
  END_GAME: Symbol(16),
  SHUFFLE: Symbol(9),
  DEALER_CARD_UP: Symbol(10),
  DEALER_CARD_DOWN: Symbol(17),
  EXPOSE_DEALER_CARD: Symbol(18),
}